### PR TITLE
refactor folder structure and add router to it

### PR DESCRIPTION
**Pull request by aloksingh3112**
Screenshot 2020-03-26 at 3 43 29 PM

### CODE REVIEW

**Comment by ivanoats** [comment]
What do the various folders do? No testing folder?  Can you split the router into a separate PR? I would like more architecture discussion before implementation right now.

**Review by ivanoats — APPROVED** [review]
looks good!

**Comment by ivanoats** [comment]
anyone interested in resolving the conflicts on this?

**Comment by parthsarthiprasad** [comment]
@ivanoats I'd open a PR for this,  if it's still available tasks will be 

- resolving merge conflicts,

- restructuring the folder?

**Pull request closed without merging**
